apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-optimizer-config
  namespace: mcp-optimizer
  labels:
    app: mcp-optimizer
data:
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  MAX_SOLVE_TIME: "300"
  MAX_MEMORY_MB: "2048"
  MAX_CONCURRENT_REQUESTS: "5"
  # MCP SSE server configuration for remote access
  TRANSPORT_MODE: "sse"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8000"
  PYTHONPATH: "/app/src" 